name: Automatic Test
# Specify which GitHub events will trigger a CI build

on: push
# Define a single job, build

jobs:
  build:
    # Specify an OS for the runner
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11","3.12", "3.13", "3.14"]

    #Define steps
    steps:

      # Firstly, checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4
      # Set up Python env
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      # Install dependencies
      - name: Install CFAPyX Dev Mode
        run: |
          python3 -m pip install --upgrade pip &&
          pip3 install poetry &&
          poetry install --with dev
      - name: Run pre-commit with ruff
        run: |
          poetry run pre-commit install
          poetry run pre-commit run -a
      - name: Run pytest
        run: |
          poetry run pytest